using System.Collections.Generic;

using Tao.OpenGl;

namespace UoT {
  /// <summary>
  ///   Helper class for caching textures generated by display lists.
  /// </summary>
  public class TextureCache {
    private readonly IDictionary<long, Texture> impl_ =
        new Dictionary<long, Texture>();

    public void Clear() {
      foreach (var texture in this.impl_.Values) {
        texture.Destroy();
      }
      this.impl_.Clear();
    }

    /// <summary>
    ///   O(log(n)) lookup.
    /// </summary>
    public Texture this[TextureParams textureParams] {
      get {
        var uuid = TextureCache.GetUuidForTextureParams_(textureParams);
        this.impl_.TryGetValue(uuid, out var texture);
        return texture;
      }
    }

    public void Add(TextureParams textureParams) {
      var uuid = TextureCache.GetUuidForTextureParams_(textureParams);
      if (!this.impl_.ContainsKey(uuid)) {
        this.impl_.Add(uuid, new Texture(textureParams));
      }
    }

    private static long GetUuidForTextureParams_(TextureParams textureParams) {
      long offset = textureParams.Offset;
      long imageBank = textureParams.ImageBank;

      return offset << 32 | imageBank;
    }
  }
}