using System.Collections.Generic;

using Tao.OpenGl;

namespace UoT {
  /// <summary>
  ///   Helper class for caching textures generated by display lists.
  /// </summary>
  public class TextureCache {
    private readonly IDictionary<long, Texture> impl_ =
        new Dictionary<long, Texture>();

    public void Clear() {
      // TODO: Move inside texture class.
      foreach (var kvp in this.impl_) {
        var id = kvp.Value.Data.ID;
        Gl.glDeleteTextures(1, ref id);
      }
      this.impl_.Clear();
    }

    /// <summary>
    ///   O(log(n)) lookup.
    /// </summary>
    public Texture this[TextureData data] {
      get {
        var uuid = TextureCache.GetUuidForData_(data);
        this.impl_.TryGetValue(uuid, out var texture);
        return texture;
      }
    }

    public void Add(TextureData data) {
      var uuid = TextureCache.GetUuidForData_(data);
      if (!this.impl_.ContainsKey(uuid)) {
        this.impl_.Add(uuid, new Texture(data));
      }
    }

    private static long GetUuidForData_(TextureData data) {
      long offset = data.Offset;
      long imageBank = data.ImageBank;

      return offset << 32 | imageBank;
    }
  }
}